# Generated by Django 3.0 on 2021-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
