# Generated by Django 3.0 on 2021-08-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_id',
        ),
    ]
