# Generated by Django 3.0 on 2021-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
